### PR TITLE
Closes #259

### LINKED ISSUE #259: Some minor cleanup patches and a fix for a flaw in the QoS DSCP handling
Hi,

I would like to publish some minor patches for cleanup and a small fix for the QoS object.

Here  is the patch archive:
[patches_190911.tar.gz](https://github.com/EIPStackGroup/OpENer/files/3601596/patches_190911.tar.gz)

The patch description follows:

1. This patch removes from POSIX/OpENer_PLATFORM_INCLUDES.cmake some compiler 
   defines that are internal (i.e. private) macros from <features.h>. Now the official / public
   _GNU_SOURCE define is used.
   This change also lets us get rid of the Linux specific header <linux/if.h> that was used in 
   networkconfig.c. Now including <net/if.h> suffices.
2. Cleanup: Object's class ids get same type and naming convention
   Object class ids were not declared in a uniform way in the object source headers. This fixes
   also a signed / unsigned mismatch warning.
3. Fix: QoS DSCP values should come into effect only after a restart
   IO connections used the DSCP values effective at the moment when the connection is 
   established. That could be a value already changed after boot-up by an explicit request. But 
   they should use the DSCP value active at boot-up. See Vol. 2, Section "5-7.4.2 DSCP Value 
   Attributes" at the end of the section.
4. Cleanup: Avoid warnings in POSIX/networkconfig.c
  See patch commit message.

I hope you like these patches and apply them to the OpENer tree. Only to avoid that they will
be forgotten I would like to remind you that for the bug report #214 I provided also three cleanup
patches (together with a proposed solution). I would like to have these three patches applied to the tree, also.

Best regards,
    Stefan

### PR DESCRIPTION
**Pull request by CapXilinx**

### CODE REVIEW

File: source/src/cip/cipassembly.c [hunk 1]
```diff
@@ -31,7 +31,7 @@ EipStatus SetAssemblyAttributeSingle(CipInstance *const instance,
  */
 CipClass *CreateAssemblyClass(void) {
   /* create the CIP Assembly object with zero instances */
-  CipClass *assembly_class = CreateCipClass(kCipAssemblyClassCode, 0, /* # class attributes*/
+  CipClass *assembly_class = CreateCipClass(kCipAssemblyClassId, 0, /* # class attributes*/
```
Comment (CapXilinx) [inline source/src/cip/cipassembly.c]: The official name is Class Code (see Vol. 1 4-3), so this should be reverted

File: source/src/cip/cipassembly.c [hunk 2]
```diff
@@ -63,7 +63,7 @@ EipStatus CipAssemblyInitialize(void) {
 }
 
 void ShutdownAssemblies(void) {
-  CipClass *assembly_class = GetCipClass(kCipAssemblyClassCode);
+  CipClass *assembly_class = GetCipClass(kCipAssemblyClassId);
```
Comment (CapXilinx) [inline source/src/cip/cipassembly.c]: same here, official name Class Code

File: source/src/cip/cipassembly.c [hunk 3]
```diff
@@ -80,7 +80,7 @@ void ShutdownAssemblies(void) {
 CipInstance *CreateAssemblyObject(const EipUint32 instance_id,
                                   EipByte *const data,
                                   const EipUint16 data_length) {
-  CipClass *assembly_class = GetCipClass(kCipAssemblyClassCode);
+  CipClass *assembly_class = GetCipClass(kCipAssemblyClassId);
```
Comment (CapXilinx) [inline source/src/cip/cipassembly.c]: same here, official name Class Code

File: source/src/cip/cipassembly.h [hunk 4]
```diff
@@ -9,8 +9,8 @@
 #include "typedefs.h"
 #include "ciptypes.h"
 
-/** @brief Assembly Class Code */
-static const int kCipAssemblyClassCode = 0x04;
+/** @brief Assembly class id */
+static const EipUint16 kCipAssemblyClassId = 0x04u;
```
Comment (CapXilinx) [inline source/src/cip/cipassembly.h]: That's a good hint, but better to use CipUint (Eip types are a leftover, which should be removed I think)

File: source/src/cip/cipcommon.c [hunk 5]
```diff
@@ -443,7 +443,7 @@ EipStatus GetAttributeSingle(CipInstance *RESTRICT const instance,
        */
 
       if (attribute->type == kCipByteArray
-          && instance->cip_class->class_id == kCipAssemblyClassCode) {
+          && instance->cip_class->class_id == kCipAssemblyClassId) {
```
Comment (CapXilinx) [inline source/src/cip/cipcommon.c]: same here, official name Class Code

File: source/src/cip/cipconnectionmanager.c [hunk 6]
```diff
@@ -207,7 +207,7 @@ EipStatus ConnectionManagerInit(EipUint16 unique_connection_id) {
   InitializeConnectionManagerData();
 
   CipClass *connection_manager = CreateCipClass(
-    g_kCipConnectionManagerClassCode,   /* class ID */
+    kCipConnectionManagerClassId,   /* class ID */
```
Comment (CapXilinx) [inline source/src/cip/cipconnectionmanager.c]: same here, official name Class Code

File: source/src/cip/cipconnectionmanager.c [hunk 7]
```diff
@@ -233,8 +233,8 @@ EipStatus ConnectionManagerInit(EipUint16 unique_connection_id) {
 
   g_incarnation_id = ( (EipUint32) unique_connection_id ) << 16;
 
-  AddConnectableObject(kCipMessageRouterClassCode, EstablishClass3Connection);
-  AddConnectableObject(kCipAssemblyClassCode, EstablishIoConnection);
+  AddConnectableObject(kCipMessageRouterClassId, EstablishClass3Connection);
```
Comment (CapXilinx) [inline source/src/cip/cipconnectionmanager.c]: same here, official name Class Code

File: source/src/cip/cipconnectionmanager.c [hunk 8]
```diff
@@ -233,8 +233,8 @@ EipStatus ConnectionManagerInit(EipUint16 unique_connection_id) {
...
+  AddConnectableObject(kCipAssemblyClassId, EstablishIoConnection);
```
Comment (CapXilinx) [inline source/src/cip/cipconnectionmanager.c]: same here, official name Class Code

File: source/src/cip/cipconnectionmanager.c [hunk 9]
```diff
@@ -1213,7 +1213,7 @@ EipUint8 ParseConnectionPath(
       }
 
       /* connection end point has to be the message router instance 1 */
-      if ( (class_id != kCipMessageRouterClassCode)
+      if ( (class_id != kCipMessageRouterClassId)
```
Comment (CapXilinx) [inline source/src/cip/cipconnectionmanager.c]: same here, official name Class Code

File: source/src/cip/cipconnectionmanager.h [hunk 10]
```diff
@@ -159,8 +159,8 @@ typedef enum {
 #define SEQ_LEQ16(a, b) ( (short)( (a) - (b) ) <= 0 )
 #define SEQ_GEQ16(a, b) ( (short)( (a) - (b) ) >= 0 )
 
-/** @brief Connection Manager class code */
-static const int g_kCipConnectionManagerClassCode = 0x06;
+/** @brief Connection Manager class id */
+static const EipUint16 kCipConnectionManagerClassId = 0x06u;
```
Comment (CapXilinx) [inline source/src/cip/cipconnectionmanager.h]: use CipUint

File: source/src/cip/cipethernetlink.h [hunk 11]
```diff
@@ -9,7 +9,11 @@
 #include "typedefs.h"
 #include "ciptypes.h"
 
-#define CIP_ETHERNETLINK_CLASS_CODE 0xF6
+/** @brief This Ethernet Link class id as #define is still needed for a static
+ *  initialization. */
+#define CIP_ETHERNETLINK_CLASS_ID   0xF6u
```
Comment (CapXilinx) [inline source/src/cip/cipethernetlink.h]: Class Code

File: source/src/cip/cipethernetlink.h [hunk 12]
```diff
@@ -9,7 +9,11 @@
...
+/** @brief Ethernet Link class id */
+static const EipUint16 kCipEthernetLinkClassId = CIP_ETHERNETLINK_CLASS_ID;
```
Comment (CapXilinx) [inline source/src/cip/cipethernetlink.h]: CipUint

File: source/src/cip/cipidentity.c [hunk 13]
```diff
@@ -147,7 +147,7 @@ void InitializeCipIdentiy(CipClass *class) {
 
 EipStatus CipIdentityInit() {
 
-  CipClass *class = CreateCipClass(kIdentityClassCode,
+  CipClass *class = CreateCipClass(kIdentityClassId,
```
Comment (CapXilinx) [inline source/src/cip/cipidentity.c]: Class Code

File: source/src/cip/cipidentity.h [hunk 14]
```diff
@@ -9,7 +9,8 @@
 #include "typedefs.h"
 #include "ciptypes.h"
 
-static const int kIdentityClassCode = 0x01;
+/** @brief Identity class id */
+static const EipUint16 kIdentityClassId = 0x01u;
```
Comment (CapXilinx) [inline source/src/cip/cipidentity.h]: CipUint

File: source/src/cip/cipioconnection.c [hunk 15]
```diff
@@ -111,7 +111,7 @@ EipUint16 SetupIoConnectionOriginatorToTargetConnectionPoint(
   CipConnectionObject *const io_connection_object,
   CipConnectionObject *const RESTRICT connection_object
   ) {
-  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassCode);
+  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassId);
```
Comment (CapXilinx) [inline source/src/cip/cipioconnection.c]: class code

File: source/src/cip/cipioconnection.c [hunk 16]
```diff
@@ -218,7 +218,7 @@ EipUint16 SetupIoConnectionTargetToOriginatorConnectionPoint(
   }
 
   /*setup producer side*/
-  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassCode);
+  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassId);
```
Comment (CapXilinx) [inline source/src/cip/cipioconnection.c]: class code

File: source/src/cip/cipioconnection.c [hunk 17]
```diff
@@ -621,7 +621,7 @@ EipStatus OpenMulticastConnection(
 
 EipUint16 HandleConfigData(CipConnectionObject *connection_object) {
 
-  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassCode);
+  CipClass *const assembly_class = GetCipClass(kCipAssemblyClassId);
```
Comment (CapXilinx) [inline source/src/cip/cipioconnection.c]: class code

File: source/src/cip/cipmessagerouter.c [hunk 18]
```diff
@@ -77,7 +77,7 @@ void InitializeCipMessageRouterClass(CipClass *cip_class) {
 
 EipStatus CipMessageRouterInit() {
 
-  CipClass *message_router = CreateCipClass(kCipMessageRouterClassCode, /* class ID*/
+  CipClass *message_router = CreateCipClass(kCipMessageRouterClassId, /* class ID*/
```
Comment (CapXilinx) [inline source/src/cip/cipmessagerouter.c]: class code

File: source/src/cip/cipmessagerouter.h [hunk 19]
```diff
@@ -9,12 +9,13 @@
 #include "typedefs.h"
 #include "ciptypes.h"
 
-static const int kCipMessageRouterClassCode = 0x02;
+/** @brief Message Router class id */
+static const EipUint16 kCipMessageRouterClassId = 0x02u;
```
Comment (CapXilinx) [inline source/src/cip/cipmessagerouter.h]: class code + CipUint

File: source/src/cip/cipqos.c [hunk 20]
```diff
@@ -25,6 +25,24 @@ CipUsint dscp_low = 31; /**< DSCP value for CIP transport class 0/1 low priority
...
                                 and all other EtherNet/IP encapsulation messages */
 
+/** @brief Hidden copy of data that need to be frozen on boot-up
+ *
+ *  The QoS DSCP values can be changed from the EIP network but the changes should come
+ *  into effect only after a restart. Therefore we take a copy here when the network is
+ *  initialized in NetworkHandlerInitialize() and CipQosGetDscpPriority() is called the
+ *  first time.
+ */
+static bool s_is_frozen = false;
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: find a better name, conveying its meaning

File: source/src/cip/cipqos.c [hunk 21]
```diff
@@ -25,6 +25,24 @@ CipUsint dscp_low = 31; /**< DSCP value for CIP transport class 0/1 low priority
...
+static struct {
+  CipUsint dscp_event;
+  CipUsint dscp_general;
+  CipUsint dscp_urgent;
+  CipUsint dscp_scheduled;
+  CipUsint dscp_high;
+  CipUsint dscp_low;
+  CipUsint dscp_explicit;
+} s_frozen;
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: give struct a type name, and a better var name

File: source/src/cip/cipqos.c [hunk 22]
```diff
@@ -88,38 +106,51 @@ EipStatus SetAttributeSingleQoS(
...
+    s_frozen.dscp_general = dscp_general;
+    s_frozen.dscp_urgent = dscp_urgent;
+    s_frozen.dscp_scheduled = dscp_scheduled;
+    s_frozen.dscp_high = dscp_high;
+    s_frozen.dscp_low = dscp_low;
+    s_frozen.dscp_explicit = dscp_explicit;
+  }
 
-  CipUsint priority_value = dscp_explicit;
+  priority_value = s_frozen.dscp_explicit;
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: move var declaration to this point

File: source/src/cip/cipqos.c [hunk 23]
```diff
@@ -88,38 +106,51 @@ EipStatus SetAttributeSingleQoS(
...
-      priority_value = dscp_explicit;
+      priority_value = s_frozen.dscp_explicit;
       break;
   }
   return priority_value;
 }
 
 void InitializeCipQos(CipClass *class) {
-  CipClass *meta_class = class->class_instance.cip_class;
+  /* avoid compiler  warning: CipClass *meta_class = class->class_instance.cip_class; */
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: remove code

File: source/src/cip/cipqos.c [hunk 24]
```diff
@@ -88,38 +106,51 @@ EipStatus SetAttributeSingleQoS(
...
 }
 
 EipStatus CipQoSInit() {
 
   CipClass *qos_class = NULL;
 
-  if( ( qos_class = CreateCipClass(kCipQoSClassCode,
+  if( ( qos_class = CreateCipClass(kCipQoSClassId,
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: classcode

File: source/src/cip/cipqos.h [hunk 25]
```diff
@@ -16,12 +16,13 @@
 #include "ciptypes.h"
 #include "cipconnectionmanager.h"
 
-static const EipUint16 kCipQoSClassCode = 0x48; /**< QoS Object class code */
+/** @brief QoS Object class id */
+static const EipUint16 kCipQoSClassId = 0x48u;
```
Comment (CapXilinx) [inline source/src/cip/cipqos.h]: class code + CipUint

File: source/src/cip/ciptcpipinterface.c [hunk 26]
```diff
@@ -22,7 +22,7 @@ CipDword configuration_capability_ = 0x04; /**< #2  This is a default value mean
 CipDword configuration_control_ = 0x02; /**< #3  This is a TCP/IP object attribute. 0x02 means that the device shall obtain its interface configuration values via DHCP. */
 CipEpath physical_link_object_ = /**< #4 */
 { 2, /**< EIP_UINT16 (UINT) PathSize in 16 Bit chunks*/
-  CIP_ETHERNETLINK_CLASS_CODE, /**< EIP_UINT16 ClassID*/
+  CIP_ETHERNETLINK_CLASS_ID, /**< EIP_UINT16 ClassID*/
```
Comment (CapXilinx) [inline source/src/cip/ciptcpipinterface.c]: class code

File: source/src/cip/ciptcpipinterface.c [hunk 27]
```diff
@@ -165,7 +165,8 @@ EipStatus SetAttributeSingleTcp(
 EipStatus CipTcpIpInterfaceInit() {
   CipClass *tcp_ip_class = NULL;
 
-  if ( ( tcp_ip_class = CreateCipClass(kCipTcpIpInterfaceClassCode, 0, /* # class attributes*/
+  if ( ( tcp_ip_class = CreateCipClass(kCipTcpIpInterfaceClassId, /* class ID*/
```
Comment (CapXilinx) [inline source/src/cip/ciptcpipinterface.c]: class code (also in comment)

File: source/src/cip/ciptcpipinterface.h [hunk 28]
```diff
@@ -18,7 +18,8 @@ extern CipString hostname_;
 
 extern CipTcpIpNetworkInterfaceConfiguration interface_configuration_;
 
-static const EipUint16 kCipTcpIpInterfaceClassCode = 0xF5; /**< TCP/IP Interface Object class code */
+/** @brief TCP/IP Interface class id */
+static const EipUint16 kCipTcpIpInterfaceClassId = 0xF5u;
```
Comment (CapXilinx) [inline source/src/cip/ciptcpipinterface.h]: class code

File: source/src/cip/cipqos.c [hunk 29]
```diff
@@ -88,38 +106,51 @@ EipStatus SetAttributeSingleQoS(
...
       break;
     case kConnectionObjectPriorityScheduled:
-      priority_value = dscp_scheduled;
+      priority_value = s_frozen.dscp_scheduled;
       break;
     case kConnectionObjectPriorityUrgent:
-      priority_value = dscp_urgent;
+      priority_value = s_frozen.dscp_urgent;
       break;
     default:
```
Comment (CapXilinx) [inline source/src/cip/cipqos.c]: update to also have kConnectionObjectPriorityExplicit

File: source/src/ports/generic_networkhandler.c [hunk 30]
```diff
@@ -194,7 +194,7 @@ EipStatus NetworkHandlerInitialize(void) {
 
   /* have QoS DSCP explicit appear on UDP responses to unicast messages */
   if (SetQosOnSocket( g_network_status.udp_unicast_listener,
-                     GetPriorityForSocket(0xFFFF) ) != 0) {
+                     CipQosGetDscpPriority(0xFFFF) ) != 0) {
```
Comment (CapXilinx) [inline source/src/ports/generic_networkhandler.c]: do not use magic number

File: source/src/ports/generic_networkhandler.c [hunk 31]
```diff
@@ -240,7 +240,7 @@ EipStatus NetworkHandlerInitialize(void) {
 
   /* have QoS DSCP explicit appear on UDP responses to broadcast messages */
   if (SetQosOnSocket( g_network_status.udp_global_broadcast_listener,
-                     GetPriorityForSocket(0xFFFF) ) != 0) {
+                     CipQosGetDscpPriority(0xFFFF) ) != 0) {
```
Comment (CapXilinx) [inline source/src/ports/generic_networkhandler.c]: replace magic number

File: source/src/ports/generic_networkhandler.c [hunk 32]
```diff
@@ -256,7 +256,7 @@ EipStatus NetworkHandlerInitialize(void) {
    * A newly accept()ed TCP socket inherits the setting from this socket.
    */
   if (SetQosOnSocket( g_network_status.tcp_listener,
-                     GetPriorityForSocket(0xFFFF) ) != 0) {
+                     CipQosGetDscpPriority(0xFFFF) ) != 0) {
```
Comment (CapXilinx) [inline source/src/ports/generic_networkhandler.c]: replace magic number

File: source/src/cip/cipassembly.c (hunk 1 above)
Comment (stm-at-esd) [reply source/src/cip/cipassembly.c]: To change this back is ok for me.

The reason for me to change the names of the constants to contain a "ClassId" postfix was that in the CipInstance the class code is memorized in the "class_id" member. Therefore in some parts of the code there was a comparison like "instance->cip_class->class_id == kCipAssemblyClassCode". I found it counter intuitive to compare a "class_id" with a "k*ClassCode" constant.

To be completely in line with the spec the member variable should then be named "class_code" and the constants also "k*ClassCode".

File: source/src/cip/cipassembly.c (hunk 2 above)
Comment (stm-at-esd) [reply source/src/cip/cipassembly.c]: same here, ...

File: source/src/cip/cipassembly.h (hunk 4 above)
Comment (stm-at-esd) [reply source/src/cip/cipassembly.h]: It's fine that I now know that the Eip* types are deprecated now. I will use the Cip* types then.

Here also the comment needs to some attention and also must be reverted back to "Class Code"

File: source/src/cip/cipassembly.c (hunk 3 above)
Comment (stm-at-esd) [reply source/src/cip/cipassembly.c]: same revert here ...

File: source/src/cip/cipcommon.c (hunk 5 above)
Comment (stm-at-esd) [reply source/src/cip/cipcommon.c]: same revert here ...

File: source/src/cip/cipconnectionmanager.c (hunk 6 above)
Comment (stm-at-esd) [reply source/src/cip/cipconnectionmanager.c]: Here the constant keeps the "ClassCode" prefix but loses the "g_" prefix.

File: source/src/cip/cipconnectionmanager.c (hunk 7 above)
Comment (stm-at-esd) [reply source/src/cip/cipconnectionmanager.c]: same revert here ...

Comment (stm-at-esd) [inline source/src/cip/cipconnectionmanager.c]: same revert here ...

File: source/src/cip/cipconnectionmanager.c (hunk 9 above)
Comment (stm-at-esd) [reply source/src/cip/cipconnectionmanager.c]: same revert here ..., but you see it here compared with "class_id"

File: source/src/cip/cipconnectionmanager.h (hunk 10 above)
Comment (stm-at-esd) [reply source/src/cip/cipconnectionmanager.h]: Here the constant keeps the "ClassCode" prefix but loses the "g_" prefix. Needs also comment revert.

File: source/src/cip/cipethernetlink.h (hunk 11 above)
Comment (stm-at-esd) [reply source/src/cip/cipethernetlink.h]: same revert here ...

File: source/src/cip/cipethernetlink.h (hunk 12 above)
Comment (stm-at-esd) [reply source/src/cip/cipethernetlink.h]: same revert here ...

File: source/src/cip/cipidentity.h (hunk 14 above)
Comment (stm-at-esd) [reply source/src/cip/cipidentity.h]: same revert here ... but adopt CipUint

File: source/src/cip/cipioconnection.c (hunk 15 above)
Comment (stm-at-esd) [reply source/src/cip/cipioconnection.c]: same revert here ...

File: source/src/cip/cipioconnection.c (hunk 16 above)
Comment (stm-at-esd) [reply source/src/cip/cipioconnection.c]: same revert here ...

File: source/src/cip/cipioconnection.c (hunk 17 above)
Comment (stm-at-esd) [reply source/src/cip/cipioconnection.c]: same revert here ...

File: source/src/cip/cipmessagerouter.c (hunk 18 above)
Comment (stm-at-esd) [reply source/src/cip/cipmessagerouter.c]: same revert here ..., adjust comment

File: source/src/cip/cipmessagerouter.h (hunk 19 above)
Comment (stm-at-esd) [reply source/src/cip/cipmessagerouter.h]: ok

File: source/src/cip/cipqos.c (hunk 20 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: comment below ...

File: source/src/cip/cipqos.c (hunk 21 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: My reason to give the variable neither a struct name nor a type definition was that this variable is static and there should only be a single instance of it (as long as the code doesn't support multiple EIP ports). Not declaring a structure type nor giving a type definition should deter the user from creating another instance.

Now having looked at the code again perhaps the "bool s_is_frozen" variable could be made to a member of the structure (s_frozen) something like "bool valid;".
And in turn the struct could be named "s_dscp_bootup_state".

File: source/src/cip/cipqos.c (hunk 22 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: ok ...

File: source/src/cip/cipassembly.c (hunk 1 above)
Comment (CapXilinx) [reply source/src/cip/cipassembly.c]: Oh, thanks. You are right this is then counterintuitive. so I will also change this.

My reasoning for this is, bacl when I took over development a lot of variabables and constants were named differently than in the CIP spec. which made it very hard to understand the code.

File: source/src/cip/cipassembly.c (hunk 2 above)
Comment (CapXilinx) [reply source/src/cip/cipassembly.c]: Yeah. these are more markers for me, to not miss the needed changes. Eclipse is not the best tool for refactoring C code :)

File: source/src/cip/cipassembly.h (hunk 4 above)
Comment (CapXilinx) [reply source/src/cip/cipassembly.h]: Thanks for the hint. Regarding the Eip types, I have probably some similar traps still left in the code and undocumented. I have to learn to better convey design decisions and fix some documentation. now that you are also working on the code :) Sorry for that!

File: source/src/cip/cipqos.c (hunk 29 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: To have another case label with kConnectionObjectPriorityExplicit may be nice but the "enum {} kConnectionObjectPriority" from cipconnectionobject.h doesn't have such a member. I didn't dare to add such an enum constant because I'm not familiar with the internals of that module.

The lack of kConnectionObjectPriorityExplicit also has its impact on the code with  CipQosGetDscpPriority(0xFFFF) in generic_networkhandler.c.

So if there are no side effects from adding kConnectionObjectPriorityExplicit to the mentioned enum then this change should be done.

File: source/src/cip/cipqos.c (hunk 21 above)
Comment (CapXilinx) [reply source/src/cip/cipqos.c]: I thought so, but perhaps someone out there already has an OpENer version with multiple ports (not sharing it back), so this would always put additional effort on such possible developers. Putting that into the C file (and possible marking it as Private in a comment) should suffice

File: source/src/cip/cipqos.c (hunk 23 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: ok

File: source/src/cip/cipqos.c (hunk 24 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: revert ...

File: source/src/cip/cipqos.h (hunk 25 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.h]: revert ... and comment

File: source/src/cip/ciptcpipinterface.c (hunk 26 above)
Comment (stm-at-esd) [reply source/src/cip/ciptcpipinterface.c]: revert ...

File: source/src/cip/ciptcpipinterface.c (hunk 27 above)
Comment (stm-at-esd) [reply source/src/cip/ciptcpipinterface.c]: ok

File: source/src/cip/ciptcpipinterface.h (hunk 28 above)
Comment (stm-at-esd) [reply source/src/cip/ciptcpipinterface.h]: revert ... and comment

File: source/src/cip/cipqos.c (hunk 29 above)
Comment (CapXilinx) [reply source/src/cip/cipqos.c]: Yeah. that was a wrong decision made by me, so I didn't expect you to know or fix that. This comment is more a reminder for myself to change that when I am on it. Otherwise, this might get lost

File: source/src/ports/generic_networkhandler.c (hunk 30 above)
Comment (stm-at-esd) [reply source/src/ports/generic_networkhandler.c]: as already commented before the code lacks kConnectionObjectPriorityExplicit

File: source/src/ports/generic_networkhandler.c (hunk 31 above)
Comment (stm-at-esd) [reply source/src/ports/generic_networkhandler.c]: as already commented before the code lacks kConnectionObjectPriorityExplicit

File: source/src/ports/generic_networkhandler.c (hunk 32 above)
Comment (stm-at-esd) [reply source/src/ports/generic_networkhandler.c]: as already commented before the code lacks kConnectionObjectPriorityExplicit

**Comment by CapXilinx** [comment]
Many thanks to @stm-at-esd to provide this fix! This also reminded myself that some stuff should be better documented!

File: source/src/ports/generic_networkhandler.c (hunk 31 above)
Comment (CapXilinx) [reply source/src/ports/generic_networkhandler.c]: Thanks, this is part of the "replace magic number" reminder :)

File: source/src/cip/cipassembly.h (hunk 4 above)
Comment (CapXilinx) [reply source/src/cip/cipassembly.h]: As an additional info, I am not sure why the EIP types were introduced by the original contributer, but I found that always hard to tell when to use CIP and when to use EIP types. Especially as stdint.h types are not widely available on all platforms, I see no reason for the EIP type to exist.

Comment (stm-at-esd) [reply source/src/cip/cipassembly.h]: It was my impression that the Eip* types were used for code that is used to describe data "on the wire" i. e. the EtherNet/IP wire protocol. And that on the other hand code that handles "wire independent" stuff like internal object and connection management was using the Cip* data types.

This was my interpretation of the code I've seen. Also the border between these two "worlds" can't be absolutely clear because some data from "the wire" are moved into the objects at last.

File: source/src/cip/cipqos.c (hunk 21 above)
Comment (stm-at-esd) [reply source/src/cip/cipqos.c]: I think doing so as you proposed with the typedef should be fine.

When I was authoring the original patch I also pondered if the saving of the bootup state of the DSCP values should be made explicit and a dedicated function like CipQosLockDscpBootupState() should be created. That should then be called from NetworkHandlerInitialize() before the first call to CipQosGetDscpPriority() is made.

But that still should be called from CipQosGetDscpPriority() if s_dscp_bootup_state.valid is not set.

Only as an afterthought ...

Comment (CapXilinx) [reply source/src/cip/cipqos.c]: I did it right now, similar to your proposal, but dropped the valid flag entirely in favor of a dedicated update function, which is called by the Reset function. The initial set of default values is right now a set of defines, which act as initialization values for the attributes and the currently used set of DSCP values. SetAttribute then writes into the instance attributes, but only a reset triggers the transition to the working set, via the update function.

Unfortunately my Linux VM currently behaves a bit strange, so I cannot fully test it with the CT tool.
But I will push my changes for further review.
